### ISSUE TITLE
RSA with pin code & get_next_code()

### ISSUE THREAD

**Issue by zulfikar-jkt** [andreax79/python-securid#1]
Hi, it's possible to add get rsa/otp with PIN? and also get otp next code?
because my stdid not protect with password, but must input pin to get otp code.
And not current code, but next code

Thanks a lot

**Comment by Omripresent** [comment]
I've been using this snippet to adjust the generated token and add the PIN I have to it.

```
def token_pin(t, p) -> int:
    resolved_token = 0
    for i in range(0, int(math.log10(t))+1):
        c = t % 10
        t = int(t / 10)
        c += p % 10
        p = int(p / 10)
        resolved_token += int((c % 10) * math.pow(10, i))
    return resolved_token

```

**Comment by zulfikar-jkt** [comment]
> I've been using this snippet to adjust the generated token and add the PIN I have to it.
> 
> ```
> def token_pin(t, p) -> int:
>     resolved_token = 0
>     for i in range(0, int(math.log10(t))+1):
>         c = t % 10
>         t = int(t / 10)
>         c += p % 10
>         p = int(p / 10)
>         resolved_token += int((c % 10) * math.pow(10, i))
>     return resolved_token
> ```

ok thank you. it's work
