### ISSUE TITLE
_init_ missing required arg

### ISSUE THREAD

**Issue by shott92** [andreax79/python-securid#4]
trying to execute from IDLE;
```
import securid
from securid.sdtid import SdtidFile

# Read sdtid file
sdtid = SdtidFile("_*path*_.sdtid")
# Decrypt token with password
token = sdtid.get_token(password="_*password*_")
# Generate OTP
token.now() #=> '123456'
```
I receive the following error

site-packages\securid\utils.py", line 52, in aes_ecb_encrypt
    cipher = Cipher(algorithms.AES(bytes(key)), modes.ECB())
TypeError: __init__() missing 1 required positional argument: 'backend'

Python 3.7, password used is in fact PIN
![image](https://user-images.githubusercontent.com/37227619/122581602-21068000-d04f-11eb-825f-0b6284b0e3fa.png)

**Comment by andreax79** [comment]
I'm unable to reproduce the problem. Could you please post the output of pip freeze?

**Comment by andreax79** [comment]
unable to reproduce
